"""Golden-master regression tests for WireViz rendering.

WireViz has historically had no test suite; the only CI check was "does
build_examples.py crash." This module locks the *rendered graph structure*
of every bundled example and tutorial by comparing the generated Graphviz
DOT source (``Harness.graph.source``) against the committed ``.gv`` file.

It intentionally exercises only the pure-Python parse -> data-model ->
DOT-generation path, so it needs the ``graphviz`` Python package but NOT the
``dot`` binary (PNG/SVG rendering is Graphviz-version-dependent and therefore
unsuitable for byte-exact golden comparison).

Run with either::

    pytest tests/
    python tests/test_examples_golden.py        # standalone, no pytest needed

The version-string header line is normalized out so the snapshot survives
version bumps (e.g. 0.4.1 -> 0.4.2-dev) without churn.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from wireviz import wireviz  # noqa: E402

# Every .yml under these directories that has a committed .gv baseline.
EXAMPLE_DIRS = ("examples", "tutorial")

_VERSION_COMMENT = re.compile(r"^// Graph generated by WireViz .*$", re.MULTILINE)
# Image src attributes are resolved to absolute paths that embed the machine's
# checkout location (e.g. /Users/daniel/Projects/WireViz/examples/resources/x.png).
# Collapse any directory prefix down to the repo-relative "resources/..." tail so
# the snapshot is portable across machines.
_IMG_SRC = re.compile(r'src="[^"]*/(resources/[^"]*)"')


def _normalize(dot_source: str) -> str:
    """Strip machine- and version-specific detail from DOT source.

    Removes the version-string header (survives version bumps) and rewrites
    absolute image ``src`` paths to their repo-relative ``resources/...`` form.
    """
    out = _VERSION_COMMENT.sub("// Graph generated by WireViz <version>", dot_source)
    out = _IMG_SRC.sub(r'src="\1"', out)
    return out


def discover_cases():
    """Yield (yml_path, gv_path) for every example that has a .gv baseline."""
    for subdir in EXAMPLE_DIRS:
        for yml in sorted((REPO_ROOT / subdir).glob("*.yml")):
            gv = yml.with_suffix(".gv")
            if gv.exists():
                yield yml, gv


def render_dot(yml_path: Path) -> str:
    harness = wireviz.parse(str(yml_path), return_types="harness")
    return harness.graph.source


CASES = list(discover_cases())


try:
    import pytest

    @pytest.mark.parametrize("yml_path,gv_path", CASES, ids=[c[0].stem for c in CASES])
    def test_example_matches_golden(yml_path, gv_path):
        expected = _normalize(gv_path.read_text())
        actual = _normalize(render_dot(yml_path))
        assert actual == expected, (
            f"Generated DOT for {yml_path.name} diverged from committed "
            f"{gv_path.name}. If this change is intentional, rebuild the "
            f"examples and re-commit the .gv baselines."
        )

except ImportError:  # pragma: no cover - standalone fallback
    pytest = None


def _run_standalone() -> int:
    failures = []
    for yml_path, gv_path in CASES:
        try:
            expected = _normalize(gv_path.read_text())
            actual = _normalize(render_dot(yml_path))
            if actual != expected:
                failures.append(yml_path.name)
                print(f"FAIL  {yml_path.name}: DOT output diverged from {gv_path.name}")
        except Exception as exc:  # noqa: BLE001
            failures.append(yml_path.name)
            print(f"ERROR {yml_path.name}: {type(exc).__name__}: {exc}")
    print(f"\n{len(CASES) - len(failures)}/{len(CASES)} golden snapshots matched")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(_run_standalone())
